services:
  postgres:
    image: postgres:16
    container_name: traffic-postgres
    environment:
      POSTGRES_DB: trafficdb
      POSTGRES_USER: trafficuser
      POSTGRES_PASSWORD: trafficpass
    ports:
      - "5432:5432"
    volumes:
      - traffic-postgres-data:/var/lib/postgresql/data

volumes:
  traffic-postgres-data: